### ISSUE TITLE
Update 4.0 Readme documentation

### ISSUE THREAD

**Issue by benbishopnz** [samdze/godot-native-bullets-plugin#16]
The way to set up the bullet kits seems to have changed, current docs confused me a little while setting it up.

I've made some changes locally but I'm not sure how to create a pull request.

**Comment by samdze** [comment]
Ah yeah, you mean the BulletKit creation step?
Right, it has to be updated.

Did you find other outdated parts?

**Comment by benbishopnz** [comment]
That was the main source of my confusion, yes :)
The part about selecting animated_shader.gdshader could be expanded on a little. It seems like it is necessary to add the shader for the bullet to display at all. Also, when you are configurating a bullet you need to change the file selector to display all files to be able to select the shader (not sure if this is worth mentioning.)

In the collision detection section there is a line:
`var bullet_damage = Bullet.get_bullet_property(bullet_id, "data").damage`
That should be "Bullets" rather than "Bullet"

Finally, `For best performance, toggle use_bvh off in Project Settings -> Physics -> 2d.` - I don't think this option exists anymore in Godot 4 (or it got renamed to something else.)

Thanks for the quick reply.

**Comment by samdze** [comment]
Updated the 4.x branch.

**Comment by benbishopnz** [comment]
Thank you! The plugin is great, by the way :)
