### ISSUE TITLE
client crashes when adding the bullet kit resource to the Bullets node

### ISSUE THREAD

**Issue by kennethrapp** [samdze/godot-native-bullets-plugin#2]
I made a Bullet scene, made it an autoload, attached bullets.gdns and added the bullet kit resource as shown:
![Clipboard01](https://user-images.githubusercontent.com/665097/139365064-642eb814-e4a5-4644-8f03-f4d7995de6f4.png)

At this point trying to load the main scene (which is empty) causes the preview to crash without logging an error. If I don't add the resource, the scene loads. basic_bullet_kit.tres looks like this in the inspector:

![Clipboard01](https://user-images.githubusercontent.com/665097/139365599-68519906-b3f5-4b15-af56-667583dc6572.png)

I'm using the godot icon.png as a test bullet if it matters.

**Comment by samdze** [comment]
Now the plugin has been updated.
It works a bit differently but it should work! Still compatible with only Godot 3.4 and up.
See the updated README to learn more!
