### ISSUE TITLE
CTD without errors with wrong resource type in bulletkit material 

### ISSUE THREAD

**Issue by Liquid-Squid** [samdze/godot-native-bullets-plugin#8]
Steps to reproduce:
-Create new bulletkit per readme instructions
-Assign bulletkit the animated_texture.gdshader resource instead of a new material
-Use bulletkit in a BulletsEnvironment
-Play Scene: will CTD when launched with no debug info or errors

I'm sure the crash is to be expected, but some kind of error output would be good. Better yet, limiting the selection options to shader materials only in the Material script variable for Bulletkit resources would prevent this entirely.

**Comment by samdze** [comment]
I can't reproduce the assignment of a non-material resource to a BulletKit resource through the inspector.
Which steps did you follow?

https://user-images.githubusercontent.com/19392104/184537029-d1e3a117-f4af-41fb-a758-da2a888c64db.mp4


Which version of the plugin are you using?
Note that the Windows and Linux pre-compiled binaries are slightly outdated compared to the source code, but that shouldn't interfere with the resource assignment.
